version: '2'

services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Iskids01! 
            POSTGRES_DB: adopta
        ports:
            - "5432:5432" # for local dev access
        volumes:
            - postgres:/var/lib/postgresql/data
    web:
        build: .
        entrypoint: /usr/local/bin/docker-entrypoint-dev.sh
        command: [ "bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0" ]
        volumes:
            - .:/usr/src/app
            - ./docker-entrypoint-dev.sh:/usr/local/bin/docker-entrypoint-dev.sh
        ports:
            - "3000:3000"
        environment:
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: Iskids01!
            DB_NAME: adopta

        depends_on:
            - db
        restart: on-failure

volumes:
    postgres:
